code_cats_front_homepage:
    pattern:  /
    defaults: { _controller: CodeCatsFrontBundle:Default:index }

code_cats_front_users:
    pattern: /users/index
    defaults: { _controller: CodeCatsFrontBundle:User:index }

code_cats_front_user_profile:
    pattern: /user/{id}
    defaults: { _controller: CodeCatsFrontBundle:User:profile }

code_cats_front_statistics:
    pattern: /statistics/index
    defaults: { _controller: CodeCatsFrontBundle:Statistics:index }

code_cats_front_technology:
    pattern: /technology/index
    defaults: { _controller: CodeCatsFrontBundle:Technology:index }

code_cats_front_technology_show:
    pattern: /technology/single/{id}
    defaults: { _controller: CodeCatsFrontBundle:Technology:show }