#-----------------------------------------------------------------------------------------------------------------------
code_cats_panel_language:
    pattern: /language/{locale}
    defaults: { _controller: CodeCatsPanelBundle:Language:switchLanguage }
switch_language:
    pattern: /switch-language
    defaults: { _controller: CodeCatsPanelBundle:Language:switchLanguage }

code_cats_panel_homepage:
    pattern:  /
    defaults: { _controller: CodeCatsPanelBundle:Default:index }

login_check:
    path: /login_check
login:
    path: /login
    defaults: { _controller: CodeCatsPanelBundle:User:login }
account:
    path: /
logout:
    path: /logout
    defaults: { _controller: CodeCatsPanelBundle:User:logout }
register:
    path: /register
    defaults: { _controller: CodeCatsPanelBundle:User:register }
#-----------------------------------------------------------------------------------------------------------------------

test:
    pattern: /test
    defaults: { _controller: CodeCatsPanelBundle:Test:test }
test2:
    pattern: /testid/{id}
    defaults: { _controller: CodeCatsPanelBundle:Test:testId }


code_cats_panel_user_get:
    pattern: /user
    defaults: { _controller: CodeCatsPanelBundle:User:get }
    methods: [GET]

code_cats_panel_user_update:
    pattern: /user
    defaults: { _controller: CodeCatsPanelBundle:User:update }
    methods: [POST]


code_cats_panel_progress_get:
    pattern: /progress
    defaults: { _controller: CodeCatsPanelBundle:Progress:get }
    methods: [GET]

code_cats_panel_progress_update:
    pattern: /progress/{id}
    defaults: { _controller: CodeCatsPanelBundle:Progress:update }
    methods: [PUT]

code_cats_panel_progress_create:
    pattern: /progress
    defaults: { _controller: CodeCatsPanelBundle:Progress:create }
    methods: [POST]

code_cats_panel_progress_delete:
    pattern: /progress/{id}
    defaults: { _controller: CodeCatsPanelBundle:Progress:delete }
    methods: [DELETE]


code_cats_panel_category_get:
    pattern: /category
    defaults: { _controller: CodeCatsPanelBundle:Category:get }
    methods: [GET]

code_cats_panel_category_update:
    pattern: /category/{id}
    defaults: { _controller: CodeCatsPanelBundle:Category:update }
    methods: [PUT]

code_cats_panel_category_create:
    pattern: /category
    defaults: { _controller: CodeCatsPanelBundle:Category:create }
    methods: [POST]

code_cats_panel_category_delete:
    pattern: /category/{id}
    defaults: { _controller: CodeCatsPanelBundle:Category:delete }
    methods: [DELETE]


code_cats_panel_phone_get:
    pattern: /phone
    defaults: { _controller: CodeCatsPanelBundle:Phone:getByUser }
    methods: [GET]

code_cats_panel_phone_update:
    pattern: /phone/{id}
    defaults: { _controller: CodeCatsPanelBundle:Phone:update }
    methods: [PUT]

code_cats_panel_phone_create:
    pattern: /phone
    defaults: { _controller: CodeCatsPanelBundle:Phone:create }
    methods: [POST]

code_cats_panel_phone_delete:
    pattern: /phone/{id}
    defaults: { _controller: CodeCatsPanelBundle:Phone:delete }
    methods: [DELETE]


code_cats_panel_avatar_get:
    pattern: /uploads/avatars/{name}
    defaults: { _controller: CodeCatsPanelBundle:Avatar:get }
    methods: [GET]

code_cats_panel_avatar_session_get:
    pattern: /user-avatar
    defaults: { _controller: CodeCatsPanelBundle:Avatar:getByUserSession }
    methods: [GET]


code_cats_panel_company_email_get:
    pattern: /company-email
    defaults: { _controller: CodeCatsPanelBundle:CompanyEmail:get }
    methods: [GET]

code_cats_panel_company_email_update:
    pattern: /company-email/{id}
    defaults: { _controller: CodeCatsPanelBundle:CompanyEmail:update }
    methods: [PUT]

code_cats_panel_company_email_create:
    pattern: /company-email
    defaults: { _controller: CodeCatsPanelBundle:CompanyEmail:create }
    methods: [POST]

code_cats_panel_company_email_delete:
    pattern: /company-email/{id}
    defaults: { _controller: CodeCatsPanelBundle:CompanyEmail:delete }
    methods: [DELETE]
