code_cats_panel_homepage:
  pattern:  /
  defaults: { _controller: CodeCatsPanelBundle:Default:index }

login_check:
  path: /login_check

login:
  path: /login
  defaults: { _controller: CodeCatsPanelBundle:User:login }

account:
  path: /

logout:
  path: /logout
  defaults: { _controller: CodeCatsPanelBundle:User:logout }
