parameters:
#    code_cats_panel.example.class: CodeCats\PanelBundle\Example

services:
#    code_cats_panel.example:
#        class: %code_cats_panel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    code_cats.locale_listener:
        class: CodeCats\PanelBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    code_cats.user_manager:
        class: CodeCats\PanelBundle\EventListener\UserManager
        arguments: [@service_container]
        tags:
            - {name: doctrine.event_listener, event: prePersist }
            - {name: doctrine.event_listener, event: preUpdate }
